name: Code Quality and Formatting

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Important: fetch full git history and allow pushing back to PR
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Dependencies
      run: |
        composer install --no-interaction --prefer-dist

    - name: Run Laravel Pint
      run: |
        vendor/bin/pint

    - name: Commit linted files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Fixes coding style"
