name: PHP Tests

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.3']
        dependency-version: ['prefer-stable']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, gd, xml, dom, json
        coverage: xdebug
        tools: composer:v2, pest

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Dependencies
      run: |
        composer install --no-interaction --prefer-dist

    - name: Run PHPStan Static Analysis
      run: composer analyse

    - name: Run Pest Tests
      run: composer test

    - name: Run Pest Coverage
      run: composer test-coverage